Feature/share button
Traewelldroid/traewelldroid pull request #61
Opened 2022-10-08 14:49 UTC by DRSchlaubi

https://twitter.com/SchlaumeierTVDE/status/1578759156772745216

2022-10-10 17:51 UTC, jheubuch commented
I think that's a good idea, but I also think, that the "socialText"-Attribute of Träwelling-API could be used for sharing the status. Also by that we would lose the "one-click-check-in-clone"-feature... Do you have any ideas about moving the share button to another location? (like Floating Action Button whatever?)

2022-10-10 18:20 UTC, DRSchlaubi commented
I thought about this for a while but I have no idea about where to put the share button

tbh i am not a huge fan of the floating action button

2022-11-17 12:49 UTC, jheubuch requested changes

2022-11-17 12:49 UTC, jheubuch commented on app/src/main/res/drawable/ic_location.xml
> +<vector android:height="24dp" android:tint="#000000"
```suggestion
<vector android:height="24dp" android:tint="?attr/colorControlNormal"
```

2022-11-17 12:49 UTC, jheubuch commented on app/src/main/res/drawable/ic_home.xml
> +<vector android:height="24dp" android:tint="#000000"
```suggestion
<vector android:height="24dp" android:tint="?attr/colorControlNormal"
```

2022-11-17 13:56 UTC, jheubuch approved these changes

2022-11-17 13:57 UTC, jheubuch commented
Please squash commits on merge and use Gitmoji for the commit message :)

2022-11-17 14:07 UTC, merged