Use default status visibility
Traewelldroid/traewelldroid pull request #79
Opened 2022-11-21 15:05 UTC by DRSchlaubi

Depending on https://github.com/Traewelling/traewelling/pull/1196

2022-11-23 09:31 UTC, jheubuch requested changes

2022-11-23 09:31 UTC, jheubuch commented on app/src/main/java/de/hbch/traewelling/api/models/user/User.kt
> +    @SerializedName("default_status_visibility") val defaultStatusVisibility: StatusVisibility
```suggestion
    @SerializedName("defaultStatusVisibility") val defaultStatusVisibility: StatusVisibility
```

You changed this name in the other PR :)

2022-11-23 10:41 UTC, DRSchlaubi commented
forgot to push

2022-11-23 12:44 UTC, jheubuch approved these changes

2022-11-23 12:44 UTC, jheubuch commented
Pls do not merge until a new Träwelling release is created

2022-11-28 12:30 UTC, DRSchlaubi commented
Change has been deployed

2022-11-28 12:30 UTC, merged